### PR TITLE
 added crypto_box_easy, crypto_box_open_easy and crypto_box_seed_keypair

### PR DESCRIPTION
**Pull request by ne0h**

### CODE REVIEW

**Comment by ne0h** [comment]
added crypto_box_easy, crypto_box_open_easy and crypto_box_seed_keypair

**Comment by stef** [comment]
nice job! thanks for the contrib!

**Comment by ne0h** [comment]
No problem :)

**Comment by hsivonen** [comment]
What's the purpose of exposing the `_easy` variants to Python? It seems to me it would make more sense to keep only the old `crypto_box` and `crypto_box_open` python signatures but replace the implementations with these that call the `_easy` variants behind the scenes for less Python-side copying.

**Comment by stef** [comment]
hmmm, you might be right.

**Comment by stef** [comment]
neOh, i think it makes sense to remove the _easy functions in general. this also seems to be an issue here: https://github.com/stef/pysodium/pull/34

**Comment by ne0h** [comment]
I would prefer to use the same methods as in libsodium itself. Libsodium uses _easy-methods so I think we should use them, too.

**Comment by stef** [comment]
_easy methods are used in sodium to wrap the padding, we do this already in the non-"_easy" methods. so it's enough to alias the non-easyones to the easyones, like
crypto_box_easy = crypto_box

would that work for you?

**Comment by ne0h** [comment]
I think it is important that someone who is not familiar with pysodium sees the same methods as in libsodium. Therefore shouldn't we rename the non-"_easy" methods to "_easy"?

**Pull request merged**
