### PR TITLE
adds crypto_pwhash* and tests

### PR DESCRIPTION
**Pull request by tacitus-aedifex**
@stef more functions i need.

### CODE REVIEW

**Comment by tacitus-aedifex** [comment]
@stef, ping.

**Comment by stef** [comment]
great! can you update the readme as well please?

**Comment by stef** [comment]
after merging the sk_to_seed PR this branch has conflicts, can you solve them, with the README together please?

**Comment by tacitus-aedifex** [comment]
right away :)

**Comment by tacitus-aedifex** [comment]
@stef alright, i've updated the README.md and rebased the branch to the latest revision of master.

**Comment by stef** [comment]
uhoh, there seems to be something missing? the travis test fails with:
name 'crypto_pwhash_ALG_DEFAULT' is not defined

**Comment by tacitus-aedifex** [comment]
found it.  there was a mismatch between the sodium_version checks.  i cloned libsodium and checked out the code at different release tags and grep'd for symbols to confirm the changes i made.

**Comment by tacitus-aedifex** [comment]
hrm...same error.  i don't get it :/

**Comment by tacitus-aedifex** [comment]
@stef I don't know why it's not picking up that symbol.  The `crypto_generichash` function has it's `outlen` parameter defaulting to `crypto_generichash_BYTES` which is defined the same way as the `crypto_pwhash_ALG_DEFAULT` symbol.  The only different is `crypto_pwhash_ALG_DEFAULT` is in a sodium_version check if block.

**Comment by stef** [comment]
maybe the libsodium is too old? and the checks need also be guarded against this problem? then the tests don't run, only, when the libsodium supports it:

Setting up libsodium13 (1.0.3-1)

**Comment by stef** [comment]
can you try to update https://github.com/stef/pysodium/blob/master/.travis.yml#L10 so it refers to libsodium18 instead of 13?

**Comment by tacitus-aedifex** [comment]
Is that going to fix it? Does the "18" refer to 1.0.8?  That's not new enough.  It needs 1.0.9 minimum.

**Comment by stef** [comment]
i believe it installs 1.0.10

**Comment by tacitus-aedifex** [comment]
@stef great, now i have to learn travisci :)

**Comment by stef** [comment]
hmmm, damn, why do these maintainers put numbers in the pkg name? why? anyway, it seems 18 is not available on ubuntu, need to check out what is available on ubuntu and put that into the travis config. very stupid. if it would be only libsodium it would go automatically.

**Comment by stef** [comment]
according to https://launchpad.net/ubuntu/+source/libsodium libsodium18 is not in wily, only libsodium13 (whatever the numbers mean in the pkg name)

**Comment by stef** [comment]
maybe we can hack travis to support this newer pkg

**Comment by tacitus-aedifex** [comment]
so xenial (16.04) has libsodium18 which is still only version 1.0.8.  i'm looking for 1.0.9 or newer.  i was reading the travis docs and there is a way to make this work.  let me update .travis.yml in this branch and see if i can get 1.0.10 installed as part of the build.

**Comment by tacitus-aedifex** [comment]
added shell script to d/l and install libsodium-1.0.10 from source and updated .travis.yml to use it before installing pysodium.  hopefully i figured out enough of travisci to make this work.

**Comment by tacitus-aedifex** [comment]
OK, so that worked but the test_crypto_pwhash test is failing on python 3.4 but not on python 2.7.  that's weird.

**Comment by tacitus-aedifex** [comment]
@stef so i can confirm that running under python3.4 the value of `out` on line 164 of test_pysodium.py is `b'65dda5b52ab171caf304608a43d28f4092f1240f62658406c02a1f62bce2cda1'`.  When running under python2.7 the value of `out` is `b'79db3095517c7358449d84ee3b2f81f0e9907fbd4e0bae4e0bcc6c79821427dc'`.  I'm not sure what is going on.  I'm investigating.

**Comment by stef** [comment]
probably some stupid py3 string/byte encoding snafu?

**Comment by tacitus-aedifex** [comment]
that's what it looks like.  in py3.4 it is a b'' and in py2.7 it is just a ''

**Comment by tacitus-aedifex** [comment]
by why doesn't this affect any other tests that do similar things?

**Comment by tacitus-aedifex** [comment]
in 3.4 the salt is a bytes() and in 2.7 it is a str()

**Comment by tacitus-aedifex** [comment]
it's the passwd for some reason.

py3.4:
```
PASSWD: 430006f0007200072000650006300074000
SALT: f58b94c7a369fd8a9a783e4cd75266
OUT: 65dda5b52ab171caf34608a43d28f4092f124f6265846c02a1f62bce2cda1
```

py2.7:
```
PASSWD: 436f727265637420486f727365204261747465727920537461706c65
SALT: f58b94c7a369fd8a9a783e4cd75266
OUT: 79db3095517c7358449d84ee3b2f81f0e9907fbd4ebae4ebcc6c79821427dc
```

**Comment by tacitus-aedifex** [comment]
oh, i get it.  the py34 C calling layer is the passwd as a unicode string instead of uchar bytes.

**Comment by tacitus-aedifex** [comment]
@stef alright, i've got the fix.  the trick is to encode all string parameters into UTF-8 which eliminates the difference between the way strings are stored in 3.x and 2.x.  the only problem is that in 2.x, bytes and str are both str types so sometimes the encode() function fails but that only happens if you pass a binascii.unhexlify() bytes array, so it is alright to just catch the exception and ignore it.

i captured all of this logic in a new decorator that goes through the parameters passed to the pysodium function and does the UTF-8 encoding before calling the decorated function.  so now all we have to do is add @encode_strings to any pysodium function that takes strings.

**Comment by tacitus-aedifex** [comment]
this patch is GTG now.  thanks for having patience.

**Comment by tacitus-aedifex** [comment]
@stef this PR is all green and ready to land.

**Comment by stef** [comment]
hmm, i'd say instead of hardcoding the lib to 1.0.10 we should skip tests using sodium_version_check(1, 0, 10) and wait until ubuntu adds the lib. i really don't want to change the travis.yaml whenever that happens, and even less i want to monitor when it happens. i hope you understand.

**Comment by tacitus-aedifex** [comment]
can we land this into a branch?  like the "future" branch so that we don't lose this work?

**Comment by tacitus-aedifex** [comment]
@stef alright, i'll update the patch to use the sodium_version_check() to skip tests.

**Comment by tacitus-aedifex** [comment]
@stef i reverted the changes to .travis.yml and remove the script that installs 1.0.10. i then fixed the travis failure by defining the missing symbol which is fine because the function that references the symbol will never get called due to a failed sodium_version decorator check.

**Comment by stef** [comment]
great! thanks!

**Pull request merged**
