### PR TITLE
clean up ietf aead

### PR DESCRIPTION
**Pull request by tacitus-aedifex**
Hi Stef,

Sorry I was AFK for so long.  Been super busy.  I incorporated your feedback and fixed the broken assert in the test.

### CODE REVIEW

**Comment by tacitus-aedifex** [comment]
@stef ping, just in case you can't see this PR too.

**Comment by stef** [comment]
i already merged it: https://github.com/stef/pysodium/commit/065bc0fd84f30f330952da43e47071e3b29f3a0f

is there anything in your PR that is not covered by my merge?

**Comment by tacitus-aedifex** [comment]
@stef this removes the if lines you said were unnecessary and makes the unit test pass by fixing the assert value.

**Comment by stef** [comment]
yes, but i already merged your PR from last time in this merge: 065bc0f i'm a bit confused now.

**Comment by tacitus-aedifex** [comment]
Yup, sorry.  I forgot to pull before making this branch.  Closing.  Sorry for the noise.

**Pull request closed without merging**
