### PR TITLE
adding sha512 hashing function

### PR DESCRIPTION
**Pull request by tacitus-aedifex**
this PR adds the crypto_hash_sha512 function, constants and tests.

### CODE REVIEW

**Comment by stef** [comment]
isn't this a duplicate? i see those functions already.

**Comment by damianbb** [comment]
I would be also pleased to see this function merged.
@tacitus-aedifex implementation of crypto_hash_sha512 wrapper function is very similar to already existing crypto_hash_sha512 and looks good.
This is not duplicate, sha512 and sha256 are two different functions.

**Comment by tacitus-aedifex** [comment]
crypto_hash_sha512 is not a duplicate.

FYI, this PR will need to be fixed up if my python3 support PR gets merged.

**Comment by stef** [comment]
oh, i mistook this. sorry.

**Comment by stef** [comment]
merged. thx!

**Pull request merged**
