### PR TITLE
Convert the rest of the test string to bytes

### PR DESCRIPTION
**Pull request by jvarho**

### CODE REVIEW

**Comment by stef** [comment]
oh? also pure ascii strings need b'' in py3? m(

**Comment by stef** [comment]
thx

**Comment by jvarho** [comment]
Yeah, ctypes converts unicode strings to wchar/utf16 sequences instead of char/utf8. Also happens with u"string" in python2.

**Comment by stef** [comment]
but unicode strings start with u'', in py2 at least. in py3 everything is a unicode string? what a mess this py3 is.

**Comment by jvarho** [comment]
Yeah, basically in Python2: "" == b"", in Python3: "" = u"".

**Pull request merged**
