### PR TITLE
python3 compatibility and code improvements

### PR DESCRIPTION
**Pull request by bgaifullin**
- fixed python3 compatibility
- fixed crash in macos when operating with functions of family crypto_generic_hash_*
- moved tests to separated file

### CODE REVIEW

**Comment by bgaifullin** [comment]
Hi, what I should to do, to merge changes from my fork?

**Comment by terrorbyte** [comment]
I also would like to see some progress on this.

**Comment by stef** [comment]
sorry i should've tended to this long time ago. thx terrorbyte for triggering me and noticing this stale thread in my inbox. i will review this and come back with a proposal or some action early next week. i'm terribly sorry for the delay.

**Comment by stef** [comment]
Thank you so much, quite an impressive piece of work this patch! I merged it, but the one of the tests fails:

  File "test/test_pysodium.py", line 115, in test_crypto_pwhash_scryptsalsa208sha256
    self.assertEqual(binascii.unhexlify(b'6c3c...'), output)
   AssertionError: 'l<...' != "F\x..."

(some long binary in various encodings snipped)

**Comment by terrorbyte** [comment]
It will fail in python2, due to how byte structures are handled between python3 and python2 the test returns differently. Try it in python3. If you would like I could write a check for python2 and change the test.

**Comment by stef** [comment]
i'd like to have mandatory python2 support for everything in pysodium, py3 support is optional. would you please be so kind and implement this so that it works and verifies in py2. would be awesome. thanks.

**Comment by stef** [comment]
until you port this back to py2, i'll remove this pwhash stuff, so i can release a new version of the rest. i hope you understand. thx,s

**Pull request merged**
